17.09.2024 00.30

diff --git a/Resources/PreGlusterRunTemplate b/Resources/PreGlusterRunTemplate
--- a/Resources/PreGlusterRunTemplate
+++ b/Resources/PreGlusterRunTemplate
@@ -167,45 +167,45 @@ else
 		PrimaryNIC=$(ip -o -4 addr show | awk -v ip="$INTERNALIP" '$4 ~ ip {print $2}')
 		PrimarySubnet=$(ip -o -f inet addr show $PrimaryNIC | awk '{print $4}' | cut -d '/' -f1 | sed 's/[0-9]*$/0/')"/24"
 		sudo rm -f /opt/PRISUB && sudo touch /opt/PRISUB && sudo chmod 777 /opt/PRISUB && echo "$PrimarySubnet" | sudo tee -a /opt/PRISUB > /dev/null
-	fi
-	
-	if [ ! -f /opt/WHOAMI3 ]; then
-		echo 'NON VPN CLUSTER NODE'
-	else
-		SERVICE_NAME="wg-quick@$STACKNAME"
-		TIMEOUT=300
-		INTERVAL=15
+	fi					
+fi
 
-		if systemctl list-units --type=service | grep -q "$SERVICE_NAME"; then
-		    echo "Service Found. Checking If It Is Running..."
-		    
-		    start_time=$(date +%s)
-		    while true; do
-			if CheckService; then
-			    break
-			else
-			    echo "Retrying..."	
-			fi
-			
-			current_time=$(date +%s)
-			elapsed_time=$((current_time - start_time))
-			
-			if [ "$elapsed_time" -ge "$TIMEOUT" ]; then
-			    echo "Service Error..."
-			    sudo touch $ERRORFILE && sudo chmod 777 $ERRORFILE
-			    exit 1
-			fi
-			
-			sleep "$INTERVAL"
-		    done
-		    
-		    echo "Service Is Running.Performing Further Actions..."		    
+if [ ! -f /opt/WHOAMI3 ]; then
+	echo 'NON VPN CLUSTER NODE'
+else
+	SERVICE_NAME="wg-quick@$STACKNAME"
+	TIMEOUT=300
+	INTERVAL=15
+
+	if systemctl list-units --type=service | grep -q "$SERVICE_NAME"; then
+	    echo "Service Found. Checking If It Is Running..."
+	    
+	    start_time=$(date +%s)
+	    while true; do
+		if CheckService; then
+		    break
 		else
+		    echo "Retrying..."	
+		fi
+		
+		current_time=$(date +%s)
+		elapsed_time=$((current_time - start_time))
+		
+		if [ "$elapsed_time" -ge "$TIMEOUT" ]; then
 		    echo "Service Error..."
 		    sudo touch $ERRORFILE && sudo chmod 777 $ERRORFILE
 		    exit 1
 		fi
-	fi				
+		
+		sleep "$INTERVAL"
+	    done
+	    
+	    echo "Service Is Running.Performing Further Actions..."		    
+	else
+	    echo "Service Error..."
+	    sudo touch $ERRORFILE && sudo chmod 777 $ERRORFILE
+	    exit 1
+	fi
 fi
 
 sudo touch $SUCCESSFILE && sudo chmod 777 $SUCCESSFILE 
